### PR TITLE
Fix warnings generated by purescript-0.8.0

### PR DESCRIPTION
**Pull request by telser**

### CODE REVIEW

**Comment by ethul** [comment]
Thanks!

**Comment by paf31** [comment]
Note this is a breaking change due to the syntax changes. Maybe let's wait for the core libraries to be updated and merged before releasing this?

**Comment by ethul** [comment]
Yes. Good point. Agreed on holding off on a release.

**Comment by telser** [comment]
:+1: This gets ready for the updates to the core libraries. Should help make the switch easier on day one.

**Comment by paf31** [comment]
@telser Thanks for all of the work on this, it's very much appreciated!

**Pull request merged**
